"""empty message

Revision ID: 71eea1655488
Revises: 1a986f080702
Create Date: 2024-11-13 18:32:01.937063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71eea1655488'
down_revision = '1a986f080702'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.drop_column('city')

    # ### end Alembic commands ###
