"""empty message

Revision ID: c298b79c76c1
Revises: e3924acfd215
Create Date: 2024-11-20 18:40:23.446812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c298b79c76c1'
down_revision = 'e3924acfd215'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.String(), nullable=False, server_default='Unknown'))
        batch_op.add_column(sa.Column('state', sa.String(), nullable=False, server_default='Unknown'))
        batch_op.add_column(sa.Column('image_link', sa.String(), nullable=False, server_default=' '))
        batch_op.add_column(sa.Column('website_link', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('facebook_link', sa.String(), nullable=True))

        batch_op.alter_column('city', server_default=None)
        batch_op.alter_column('state', server_default=None)
        batch_op.alter_column('image_link', server_default=None)

    with op.batch_alter_table('shows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.DateTime(), nullable=True))
        batch_op.drop_column('date')

    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.String(), nullable=False, server_default='Unknown'))
        batch_op.add_column(sa.Column('image_link', sa.String(), nullable=False, server_default=' '))
        batch_op.add_column(sa.Column('website_link', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('facebook_link', sa.String(), nullable=True))

        batch_op.alter_column('state', server_default=None)
        batch_op.alter_column('image_link', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.drop_column('facebook_link')
        batch_op.drop_column('website_link')
        batch_op.drop_column('image_link')
        batch_op.drop_column('state')

    with op.batch_alter_table('shows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('start_time')

    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.drop_column('facebook_link')
        batch_op.drop_column('website_link')
        batch_op.drop_column('image_link')
        batch_op.drop_column('state')
        batch_op.drop_column('city')

    # ### end Alembic commands ###
